# Generated by Django 5.0.2 on 2024-05-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='buye',
        ),
    ]
